server:
  port: 8092

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: bilgeadmin
    password: bilge!
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: auth-service
  datasource:
    username: 'postgres'
    password: 'root'
    url: 'jdbc:postgresql://localhost:5432/socialmediaauthDB'
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


myredis:
  host: localhost
  port: 6379

rabbitmq:
  exchange-auth: auth-exchange
  bindingKey: activated-key
  queueActivated: activated-queue

myapplication:
  feign:
    user: http://localhost:8091/api/v1
#Jwt
myjwt:
  secretkey: "secretkey"
  audience: "audience"
  issuer: "issuer"