server:
  port: 8092

spring:
  datasource:
    username: 'postgres'
    password: 'root'
    url: 'jdbc:postgresql://localhost:5432/socialmediaauthDB'
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#Jwt
myjwt:
  secretkey: "secretkey"
  audience: "audience"
  issuer: "issuer"