server:
  port: 8099


spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: elastic-service
  elasticsearch:
    uris: http://localhost:9200

myapplication:
  feign:
    user: http://localhost:8091/api/v1
    auth: http://localhost:8092/api/v1

myjwt:
  secretkey: "secretkey"
  audience: "audience"
  issuer: "issuer"