spring:

  rabbitmq:
    host: localhost
    port: 5672
    username: bilgeadmin
    password: bilge!

  mail:
    host: smtp.gmail.com
    port: 587
    username: s.k.donmez123@gmail.com
    password: 
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
rabbitmq:
  queueActivated: activated-queue
