apiVersion: v1

kind: Service

metadata:

  name: mongodb-loadbalancer

  labels:

    app: mongodbservice

spec:

  selector:

    app: mongodb

  type: LoadBalancer

  ports:

    - port: 14606

      targetPort: 27017