server:
  port: 80

spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: api-gateway-service
  application:
    name: api-gateway-service
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8092
          predicates:
            - Path= /auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: auth-service
                fallbackUri: forward:/fallback-auth-service
        - id: user-service
          uri: http://localhost:8091
          predicates:
            - Path= /user/**
          filters:
            - name: CircuitBreaker
              args:
                name: user-service
                fallbackUri: forward:/fallback-user-service
      default-filters:
        - RewritePath=/(?<segment>.*),/api/v1/$\{segment}
